import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { api } from '@/lib/api'
import { DataTableShell, OwnershipBadge, PageContainer, PageHeader, StatusBadge } from '@/components/patterns'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { usePermission, PERMISSIONS } from '@/lib/permissions'

interface Visit { id: string; name: string; visit_date: string | null; window_status: string | null; status: string }

export function VisitListPage({ subjectId }: { subjectId: string }) {
  const client = useQueryClient(); const canEnter = usePermission(PERMISSIONS.FORM_ENTER); const [showCreate, setShowCreate] = useState(false); const [name, setName] = useState(''); const [visitDate, setVisitDate] = useState(''); const [error, setError] = useState(''); const [recordingVisit, setRecordingVisit] = useState<Visit | null>(null); const [recordedDate, setRecordedDate] = useState('')
  const visits = useQuery({ queryKey: ['visits', subjectId], queryFn: async () => (await api.get<Visit[]>(`/subjects/${subjectId}/visits`)).data })
  const create = useMutation({ mutationFn: () => api.post(`/subjects/${subjectId}/visits/unscheduled`, { name, visit_date: visitDate || null }), onSuccess: () => { client.invalidateQueries({ queryKey: ['visits', subjectId] }); setShowCreate(false); setName(''); setVisitDate('') }, onError: () => setError('Could not create the unscheduled visit.') })
  const update = useMutation({ mutationFn: ({ id, action, body }: { id: string; action: string; body?: object }) => action === 'missed' ? api.post(`/visits/${id}/mark-missed`) : api.patch(`/visits/${id}`, body), onSuccess: () => client.invalidateQueries({ queryKey: ['visits', subjectId] }) })
  const items = visits.data ?? []
  return <PageContainer><PageHeader title="Visits" description="Visit instances for this subject." ownership={<OwnershipBadge owner="EDC" />} actions={canEnter ? <Button onClick={() => { setError(''); setShowCreate(true) }}>Add unscheduled visit</Button> : undefined} />
    <DataTableShell label="visits" loading={visits.isLoading} error={Boolean(visits.error)} errorMessage="Visits could not be loaded." empty={items.length === 0} emptyTitle="No visits found" emptyDescription="No visit instances are available for this subject." onRetry={() => void visits.refetch()}>
      <Table><TableHeader><TableRow>{['Visit', 'Date', 'Window', 'Status', 'Actions'].map((heading) => <TableHead key={heading}>{heading}</TableHead>)}</TableRow></TableHeader><TableBody>{items.map((item) => <TableRow key={item.id}><TableCell className="font-medium">{item.name}</TableCell><TableCell>{item.visit_date ?? '—'}</TableCell><TableCell>{item.window_status ?? '—'}</TableCell><TableCell><StatusBadge status={item.status} label="visit status" /></TableCell><TableCell><div className="flex flex-wrap gap-2">{canEnter && item.status !== 'missed' && item.status !== 'completed' ? <><Button size="sm" variant="outline" onClick={() => { setRecordingVisit(item); setRecordedDate(item.visit_date ?? '') }}>Record date</Button><Button size="sm" variant="destructive" onClick={() => update.mutate({ id: item.id, action: 'missed' })} disabled={update.isPending}>Mark missed</Button></> : null}</div></TableCell></TableRow>)}</TableBody></Table>
    </DataTableShell>
    <Dialog open={Boolean(showCreate)} onOpenChange={(open) => { setShowCreate(open); if (!open) setError('') }}><DialogContent><DialogHeader><DialogTitle>Add unscheduled visit</DialogTitle><DialogDescription>Record an additional visit instance for this subject.</DialogDescription></DialogHeader><form onSubmit={(event) => { event.preventDefault(); create.mutate() }} className="space-y-4">{error ? <Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert> : null}<div className="space-y-1.5"><Label htmlFor="visit-name">Visit name</Label><Input id="visit-name" required value={name} onChange={(event) => setName(event.target.value)} /></div><div className="space-y-1.5"><Label htmlFor="visit-date">Visit date</Label><Input id="visit-date" type="date" value={visitDate} onChange={(event) => setVisitDate(event.target.value)} /></div><DialogFooter><Button type="button" variant="outline" onClick={() => setShowCreate(false)}>Cancel</Button><Button type="submit" pending={create.isPending} loadingText="Creating…">Create</Button></DialogFooter></form></DialogContent></Dialog>
    <Dialog open={Boolean(recordingVisit)} onOpenChange={(open) => { if (!open) setRecordingVisit(null) }}><DialogContent><DialogHeader><DialogTitle>Record visit date</DialogTitle><DialogDescription>Record the date for {recordingVisit?.name}.</DialogDescription></DialogHeader><div className="space-y-1.5"><Label htmlFor="recorded-visit-date">Visit date</Label><Input id="recorded-visit-date" type="date" autoFocus value={recordedDate} onChange={(event) => setRecordedDate(event.target.value)} /></div><DialogFooter><Button type="button" variant="outline" onClick={() => setRecordingVisit(null)}>Cancel</Button><Button type="button" onClick={() => { if (recordingVisit && recordedDate) { update.mutate({ id: recordingVisit.id, action: 'date', body: { visit_date: recordedDate } }); setRecordingVisit(null) } }} disabled={!recordedDate || update.isPending} pending={update.isPending} loadingText="Recording…">Record date</Button></DialogFooter></DialogContent></Dialog>
  </PageContainer>
}
