import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { api } from '@/lib/api'
import { usePermission, PERMISSIONS } from '@/lib/permissions'

interface Visit { id: string; name: string; visit_date: string | null; window_status: string | null; status: string }

export function VisitListPage({ subjectId }: { subjectId: string }) {
  const client = useQueryClient(); const canEnter = usePermission(PERMISSIONS.FORM_ENTER); const [showCreate, setShowCreate] = useState(false); const [name, setName] = useState(''); const [visitDate, setVisitDate] = useState(''); const [error, setError] = useState('')
  const visits = useQuery({ queryKey: ['visits', subjectId], queryFn: async () => (await api.get<Visit[]>(`/subjects/${subjectId}/visits`)).data })
  const create = useMutation({ mutationFn: () => api.post(`/subjects/${subjectId}/visits/unscheduled`, { name, visit_date: visitDate || null }), onSuccess: () => { client.invalidateQueries({ queryKey: ['visits', subjectId] }); setShowCreate(false); setName(''); setVisitDate('') }, onError: () => setError('Could not create the unscheduled visit.') })
  const update = useMutation({ mutationFn: ({ id, action, body }: { id: string; action: string; body?: object }) => action === 'missed' ? api.post(`/visits/${id}/mark-missed`) : api.patch(`/visits/${id}`, body), onSuccess: () => client.invalidateQueries({ queryKey: ['visits', subjectId] }) })
  return <div className="space-y-5"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold">Visits</h1><p className="text-sm text-gray-500">Visit instances for this subject.</p></div>{canEnter && <button onClick={() => setShowCreate(true)} className="rounded bg-blue-600 px-4 py-2 text-sm text-white">Add unscheduled visit</button>}</div>{visits.isLoading ? <p className="text-gray-500">Loading…</p> : <div className="rounded-lg border bg-white"><table className="min-w-full divide-y"><thead className="bg-gray-50"><tr>{['Visit','Date','Window','Status','Actions'].map((h) => <th key={h} className="px-4 py-3 text-left text-xs font-medium uppercase text-gray-500">{h}</th>)}</tr></thead><tbody className="divide-y">{visits.data?.map((item) => <tr key={item.id}><td className="px-4 py-3 text-sm font-medium">{item.name}</td><td className="px-4 py-3 text-sm">{item.visit_date ?? '—'}</td><td className="px-4 py-3 text-sm">{item.window_status ?? '—'}</td><td className="px-4 py-3 text-sm">{item.status}</td><td className="px-4 py-3 text-sm space-x-2">{canEnter && item.status !== 'missed' && item.status !== 'completed' && <><button onClick={() => { const date = window.prompt('Visit date (YYYY-MM-DD)', item.visit_date ?? ''); if (date) update.mutate({ id: item.id, action: 'date', body: { visit_date: date } }) }} className="text-blue-700">Record date</button><button onClick={() => update.mutate({ id: item.id, action: 'missed' })} className="text-red-700">Mark missed</button></>}</td></tr>)}</tbody></table>{!visits.data?.length && <p className="p-6 text-sm text-gray-500">No visits found.</p>}</div>}{showCreate && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40"><form onSubmit={(e) => { e.preventDefault(); create.mutate() }} className="w-full max-w-md space-y-4 rounded-lg bg-white p-6"><h2 className="text-lg font-semibold">Add unscheduled visit</h2>{error && <p className="rounded bg-red-50 p-2 text-sm text-red-700">{error}</p>}<input required placeholder="Visit name" value={name} onChange={(e) => setName(e.target.value)} className="w-full rounded border px-3 py-2 text-sm" /><input type="date" value={visitDate} onChange={(e) => setVisitDate(e.target.value)} className="w-full rounded border px-3 py-2 text-sm" /><div className="flex justify-end gap-2"><button type="button" onClick={() => setShowCreate(false)} className="rounded border px-3 py-2 text-sm">Cancel</button><button className="rounded bg-blue-600 px-3 py-2 text-sm text-white">Create</button></div></form></div>}</div>
}
