"""Subject Pydantic schemas.

Satisfies Requirements:
  - 7.1: Subject metadata — bound to a published study version.
  - 7.2: Subject number unique within the study (validated at service layer);
          generated by the configured rule when not explicitly provided.
  - 7.3: Subject status transitions (enforced at service layer).
  - 7.5: Subject casebook structure with clinical status.
  - 22.2: Soft-delete retains the record.
  - 21.2: List endpoints return pagination envelope.
"""

from __future__ import annotations

from datetime import datetime
from uuid import UUID

from pydantic import Field

from app.models.subject import SubjectStatus
from app.schemas.base import BaseCreateSchema, BaseSchema

# ---------------------------------------------------------------------------
# Subject schemas (Requirement 7)
# ---------------------------------------------------------------------------


class SubjectCreate(BaseCreateSchema):
    """Request body for creating a new Subject (Requirement 7.1, 7.2).

    The site under which the subject is enrolled is supplied separately
    (path/route or explicit argument). ``subject_number`` is optional: when
    omitted, the Subject_Service generates the identifier by the configured
    rule. When provided, it is used as-is (and still enforced unique within
    the study).
    """

    site_id: UUID
    subject_number: str | None = Field(
        None,
        min_length=1,
        max_length=100,
        description="Optional; generated by the configured rule when omitted",
    )


class SubjectUpdate(BaseCreateSchema):
    """Request body for updating a Subject's metadata (partial PATCH).

    Only the subject number is editable post-creation; status changes flow
    through the dedicated transition endpoints (Requirement 7.3).
    """

    subject_number: str | None = Field(
        None, min_length=1, max_length=100, description="Updated subject identifier"
    )


class SubjectStatusTransition(BaseCreateSchema):
    """Request body for transitioning a Subject's status (Requirement 7.3)."""

    target_status: SubjectStatus


class SubjectDelete(BaseCreateSchema):
    """Request body for soft-deleting a Subject (Requirement 22.2)."""

    reason: str = Field(..., min_length=1, description="Reason for deletion")


class SubjectResponse(BaseSchema):
    """Response schema for a Subject record (Requirement 7.1)."""

    id: UUID
    study_id: UUID
    site_id: UUID
    study_version_id: UUID
    subject_number: str
    status: SubjectStatus
    created_by: UUID
    created_at: datetime
    updated_at: datetime | None = None
    deleted_at: datetime | None = None
    deleted_by: UUID | None = None
    deletion_reason: str | None = None


# ---------------------------------------------------------------------------
# Casebook schemas (Requirement 7.5)
# ---------------------------------------------------------------------------


class CasebookFormEntry(BaseSchema):
    """A form entry within a casebook visit."""

    form_instance_id: UUID | None = None
    form_definition_id: UUID | None = None
    name: str | None = None
    status: str


class CasebookVisitEntry(BaseSchema):
    """A visit entry within a casebook."""

    visit_instance_id: UUID | None = None
    visit_definition_id: UUID | None = None
    name: str | None = None
    status: str
    forms: list[CasebookFormEntry] = Field(default_factory=list)


class CasebookResponse(BaseSchema):
    """Response schema for a subject casebook (Requirement 7.5)."""

    subject_id: UUID
    subject_number: str
    status: SubjectStatus
    study_version_id: UUID
    visits: list[CasebookVisitEntry] = Field(default_factory=list)
