import * as React from 'react'
import { X } from 'lucide-react'
import { cn } from '@/lib/utils'

type DialogContextValue = { open: boolean; setOpen: (open: boolean) => void; titleId: string; descriptionId: string }
const DialogContext = React.createContext<DialogContextValue | null>(null)
export interface DialogProps { children: React.ReactNode; open?: boolean; defaultOpen?: boolean; onOpenChange?: (open: boolean) => void }
const Dialog = ({ children, open: controlledOpen, defaultOpen = false, onOpenChange }: DialogProps) => { const [uncontrolledOpen, setOpen] = React.useState(defaultOpen); const open = controlledOpen ?? uncontrolledOpen; const change = (next: boolean) => { setOpen(next); onOpenChange?.(next) }; const id = React.useId(); return <DialogContext.Provider value={{ open, setOpen: change, titleId: `${id}-title`, descriptionId: `${id}-description` }}>{children}</DialogContext.Provider> }
const DialogTrigger = React.forwardRef<HTMLButtonElement, React.ButtonHTMLAttributes<HTMLButtonElement>>(({ className, ...props }, ref) => { const context = React.useContext(DialogContext); if (!context) throw new Error('DialogTrigger must be used within Dialog'); return <button ref={ref} type="button" aria-haspopup="dialog" aria-expanded={context.open} className={cn('focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2', className)} onClick={() => context.setOpen(true)} {...props} /> })
DialogTrigger.displayName = 'DialogTrigger'
const DialogPortal = ({ children }: { children: React.ReactNode }) => <>{children}</>
const DialogOverlay = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(({ className, ...props }, ref) => <div ref={ref} className={cn('fixed inset-0 z-50 bg-black/80 data-[state=open]:animate-in', className)} {...props} />)
DialogOverlay.displayName = 'DialogOverlay'
const DialogContent = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(({ className, children, onKeyDown, ...props }, ref) => { const context = React.useContext(DialogContext); const contentRef = React.useRef<HTMLDivElement>(null); const triggerRef = React.useRef<HTMLElement | null>(null); React.useEffect(() => { if (!context?.open) return; triggerRef.current = document.activeElement as HTMLElement | null; const timer = window.setTimeout(() => { const target = contentRef.current?.querySelector<HTMLElement>('[autofocus], button:not([disabled]), input:not([disabled]), textarea:not([disabled]), select:not([disabled]), [tabindex="0"]'); target?.focus() }, 0); const onDocumentKeyDown = (event: KeyboardEvent) => { if (event.key === 'Escape') { event.preventDefault(); context.setOpen(false) } }; document.addEventListener('keydown', onDocumentKeyDown); return () => { window.clearTimeout(timer); document.removeEventListener('keydown', onDocumentKeyDown); triggerRef.current?.focus() } }, [context]); if (!context?.open) return null; return <DialogPortal><DialogOverlay onClick={() => context.setOpen(false)} /><div ref={(node) => { contentRef.current = node; if (typeof ref === 'function') ref(node); else if (ref) ref.current = node }} role="dialog" aria-modal="true" aria-labelledby={context.titleId} aria-describedby={context.descriptionId} tabIndex={-1} className={cn('fixed left-1/2 top-1/2 z-50 grid w-[calc(100%-2rem)] max-w-lg -translate-x-1/2 -translate-y-1/2 gap-4 border bg-background p-6 shadow-lg duration-200 focus:outline-none', className)} onClick={(event) => event.stopPropagation()} onKeyDown={onKeyDown} {...props}>{children}<button type="button" aria-label="Close dialog" className="absolute right-4 top-4 rounded-sm opacity-70 ring-offset-background transition-opacity hover:opacity-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2" onClick={() => context.setOpen(false)}><X className="size-4" aria-hidden="true" /></button></div></DialogPortal> })
DialogContent.displayName = 'DialogContent'
const DialogHeader = ({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) => <div className={cn('flex flex-col space-y-1.5 text-center sm:text-left', className)} {...props} />
const DialogFooter = ({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) => <div className={cn('flex flex-col-reverse gap-2 sm:flex-row sm:justify-end', className)} {...props} />
const DialogTitle = React.forwardRef<HTMLHeadingElement, React.HTMLAttributes<HTMLHeadingElement>>(({ className, ...props }, ref) => { const context = React.useContext(DialogContext); return <h2 ref={ref} id={context?.titleId} className={cn('text-lg font-semibold', className)} {...props} /> })
DialogTitle.displayName = 'DialogTitle'
const DialogDescription = React.forwardRef<HTMLParagraphElement, React.HTMLAttributes<HTMLParagraphElement>>(({ className, ...props }, ref) => { const context = React.useContext(DialogContext); return <p ref={ref} id={context?.descriptionId} className={cn('text-sm text-muted-foreground', className)} {...props} /> })
DialogDescription.displayName = 'DialogDescription'
const DialogClose = React.forwardRef<HTMLButtonElement, React.ButtonHTMLAttributes<HTMLButtonElement>>(({ className, ...props }, ref) => { const context = React.useContext(DialogContext); return <button ref={ref} type="button" className={cn('focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2', className)} onClick={() => context?.setOpen(false)} {...props} /> })
DialogClose.displayName = 'DialogClose'
export { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogOverlay, DialogPortal, DialogTitle, DialogTrigger }
