import * as React from 'react'
import { Check, ChevronDown } from 'lucide-react'
import { cn } from '@/lib/utils'

type SelectContextValue = { value?: string; onValueChange: (value: string) => void; open: boolean; setOpen: (open: boolean) => void }
const SelectContext = React.createContext<SelectContextValue | null>(null)
export interface SelectProps { value?: string; defaultValue?: string; onValueChange?: (value: string) => void; children: React.ReactNode; disabled?: boolean }
const Select = ({ value: controlledValue, defaultValue, onValueChange, children, disabled = false }: SelectProps) => { const [value, setValue] = React.useState(defaultValue); const [open, setOpen] = React.useState(false); const current = controlledValue ?? value; const selectValue = (next: string) => { setValue(next); onValueChange?.(next); setOpen(false) }; return <SelectContext.Provider value={{ value: current, onValueChange: selectValue, open, setOpen: (next) => !disabled && setOpen(next) }}>{children}</SelectContext.Provider> }
const SelectTrigger = React.forwardRef<HTMLButtonElement, React.ButtonHTMLAttributes<HTMLButtonElement>>(({ className, children, ...props }, ref) => { const context = React.useContext(SelectContext); if (!context) throw new Error('SelectTrigger must be used within Select'); return <button ref={ref} type="button" role="combobox" aria-expanded={context.open} onClick={() => context.setOpen(!context.open)} className={cn('flex h-10 w-full items-center justify-between rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50', className)} {...props}>{children}<ChevronDown className="size-4 opacity-50" aria-hidden="true" /></button> })
SelectTrigger.displayName = 'SelectTrigger'
const SelectValue = ({ placeholder, ...props }: { placeholder?: string } & React.HTMLAttributes<HTMLSpanElement>) => { const context = React.useContext(SelectContext); return <span {...props}>{context?.value || placeholder}</span> }
const SelectContent = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(({ className, children, ...props }, ref) => { const context = React.useContext(SelectContext); if (!context?.open) return null; return <div ref={ref} role="listbox" className={cn('absolute z-50 mt-1 max-h-96 min-w-[8rem] overflow-auto rounded-md border bg-popover p-1 text-popover-foreground shadow-md', className)} {...props}>{children}</div> })
SelectContent.displayName = 'SelectContent'
const SelectItem = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement> & { value: string }>(({ className, value, children, ...props }, ref) => { const context = React.useContext(SelectContext); if (!context) throw new Error('SelectItem must be used within Select'); const selected = context.value === value; return <div ref={ref} role="option" aria-selected={selected} tabIndex={0} className={cn('relative flex cursor-default select-none items-center rounded-sm py-1.5 pl-8 pr-2 text-sm outline-none focus:bg-accent focus:text-accent-foreground', className)} onClick={() => context.onValueChange(value)} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); context.onValueChange(value) } }} {...props}>{selected ? <Check className="absolute left-2 size-4" aria-hidden="true" /> : null}{children}</div> })
SelectItem.displayName = 'SelectItem'
const SelectGroup = ({ ...props }: React.HTMLAttributes<HTMLDivElement>) => <div role="group" {...props} />
const SelectLabel = ({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) => <div className={cn('py-1.5 pl-8 pr-2 text-sm font-semibold', className)} {...props} />
const SelectSeparator = ({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) => <div role="separator" className={cn('-mx-1 my-1 h-px bg-muted', className)} {...props} />
export { Select, SelectContent, SelectGroup, SelectItem, SelectLabel, SelectSeparator, SelectTrigger, SelectValue }
