import * as React from 'react'
import { X } from 'lucide-react'
import { cn } from '@/lib/utils'

type SheetContextValue = { open: boolean; setOpen: (open: boolean) => void; titleId: string; descriptionId: string }
const SheetContext = React.createContext<SheetContextValue | null>(null)
export interface SheetProps { children: React.ReactNode; open?: boolean; defaultOpen?: boolean; onOpenChange?: (open: boolean) => void }
const Sheet = ({ children, open: controlledOpen, defaultOpen = false, onOpenChange }: SheetProps) => { const [uncontrolledOpen, setOpen] = React.useState(defaultOpen); const open = controlledOpen ?? uncontrolledOpen; const change = (next: boolean) => { setOpen(next); onOpenChange?.(next) }; const id = React.useId(); return <SheetContext.Provider value={{ open, setOpen: change, titleId: `${id}-title`, descriptionId: `${id}-description` }}>{children}</SheetContext.Provider> }
const SheetTrigger = React.forwardRef<HTMLButtonElement, React.ButtonHTMLAttributes<HTMLButtonElement>>(({ className, ...props }, ref) => { const context = React.useContext(SheetContext); if (!context) throw new Error('SheetTrigger must be used within Sheet'); return <button ref={ref} type="button" aria-haspopup="dialog" aria-expanded={context.open} className={cn('focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2', className)} onClick={() => context.setOpen(true)} {...props} /> })
SheetTrigger.displayName = 'SheetTrigger'
const SheetClose = React.forwardRef<HTMLButtonElement, React.ButtonHTMLAttributes<HTMLButtonElement>>(({ className, ...props }, ref) => { const context = React.useContext(SheetContext); return <button ref={ref} type="button" className={cn('focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2', className)} onClick={() => context?.setOpen(false)} {...props} /> })
SheetClose.displayName = 'SheetClose'
const SheetContent = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement> & { side?: 'top' | 'right' | 'bottom' | 'left' }>(({ className, children, side = 'right', ...props }, ref) => { const context = React.useContext(SheetContext); const contentRef = React.useRef<HTMLDivElement>(null); const triggerRef = React.useRef<HTMLElement | null>(null); React.useEffect(() => { if (!context?.open) return; triggerRef.current = document.activeElement as HTMLElement | null; const timer = window.setTimeout(() => { contentRef.current?.querySelector<HTMLElement>('[autofocus], button:not([disabled]), input:not([disabled]), [tabindex="0"]')?.focus() }, 0); const onKeyDown = (event: KeyboardEvent) => { if (event.key === 'Escape') { event.preventDefault(); context.setOpen(false) } }; document.addEventListener('keydown', onKeyDown); return () => { window.clearTimeout(timer); document.removeEventListener('keydown', onKeyDown); triggerRef.current?.focus() } }, [context]); if (!context?.open) return null; return <><div className="fixed inset-0 z-50 bg-black/80" aria-hidden="true" onClick={() => context.setOpen(false)} /><div ref={(node) => { contentRef.current = node; if (typeof ref === 'function') ref(node); else if (ref) ref.current = node }} role="dialog" aria-modal="true" aria-labelledby={context.titleId} aria-describedby={context.descriptionId} tabIndex={-1} className={cn('fixed z-50 flex flex-col gap-4 border bg-background p-6 shadow-lg focus:outline-none', side === 'right' && 'inset-y-0 right-0 h-full w-3/4 sm:max-w-sm', side === 'left' && 'inset-y-0 left-0 h-full w-3/4 sm:max-w-sm', side === 'top' && 'inset-x-0 top-0 border-b', side === 'bottom' && 'inset-x-0 bottom-0 border-t', className)} onClick={(event) => event.stopPropagation()} {...props}>{children}<button type="button" aria-label="Close sheet" className="absolute right-4 top-4 rounded-sm opacity-70 hover:opacity-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2" onClick={() => context.setOpen(false)}><X className="size-4" aria-hidden="true" /></button></div></> })
SheetContent.displayName = 'SheetContent'
const SheetHeader = ({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) => <div className={cn('flex flex-col space-y-2 text-center sm:text-left', className)} {...props} />
const SheetFooter = ({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) => <div className={cn('mt-auto flex flex-col gap-2', className)} {...props} />
const SheetTitle = React.forwardRef<HTMLHeadingElement, React.HTMLAttributes<HTMLHeadingElement>>(({ className, ...props }, ref) => { const context = React.useContext(SheetContext); return <h2 ref={ref} id={context?.titleId} className={cn('text-lg font-semibold text-foreground', className)} {...props} /> })
SheetTitle.displayName = 'SheetTitle'
const SheetDescription = React.forwardRef<HTMLParagraphElement, React.HTMLAttributes<HTMLParagraphElement>>(({ className, ...props }, ref) => { const context = React.useContext(SheetContext); return <p ref={ref} id={context?.descriptionId} className={cn('text-sm text-muted-foreground', className)} {...props} /> })
SheetDescription.displayName = 'SheetDescription'
export { Sheet, SheetClose, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle, SheetTrigger }
