import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { api } from '@/lib/api'
import { usePermission, PERMISSIONS } from '@/lib/permissions'
import { EmptyState, ErrorState, LoadingState, OwnershipBadge, PageContainer, PageHeader } from '@/components/patterns'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Checkbox } from '@/components/ui/checkbox'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'

interface Field { id: string; label: string; variable_name: string; control_type: string; data_type: string; is_required: boolean; display_order: number }
interface Section { id: string; name: string; display_order: number; fields: Field[] }
interface FormDefinition { id: string; name: string; form_code: string; display_order: number; is_repeating: boolean; sections?: Section[] }
const CONTROL_TYPES = ['text', 'textarea', 'integer', 'decimal', 'date', 'datetime', 'time', 'radio', 'checkbox', 'dropdown', 'multi-select', 'boolean', 'file_upload', 'calculated', 'repeating_table', 'coded_term']

export function FormBuilderPage({ studyId }: { studyId: string }) {
  const queryClient = useQueryClient(); const canConfigure = usePermission(PERMISSIONS.FORM_CONFIGURE); const [selectedId, setSelectedId] = useState(''); const [form, setForm] = useState({ name: '', form_code: '', display_order: 0, is_repeating: false }); const [sectionName, setSectionName] = useState(''); const [field, setField] = useState({ label: '', variable_name: '', control_type: 'text', data_type: 'string', is_required: false }); const [error, setError] = useState('')
  const formsQuery = useQuery({ queryKey: ['form-definitions', studyId], queryFn: async () => (await api.get<FormDefinition[]>(`/studies/${studyId}/forms`)).data })
  const selected = formsQuery.data?.find((item) => item.id === selectedId)
  const detailQuery = useQuery({ queryKey: ['form-definition', selectedId], enabled: !!selectedId, queryFn: async () => (await api.get<FormDefinition>(`/forms/${selectedId}`)).data })
  const activeForm = detailQuery.data ?? selected
  const createForm = useMutation({ mutationFn: () => api.post(`/studies/${studyId}/forms`, form), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['form-definitions', studyId] }); setForm({ name: '', form_code: '', display_order: 0, is_repeating: false }) }, onError: () => setError('Could not create form. A draft study version and form.configure permission are required.') })
  const createSection = useMutation({ mutationFn: () => api.post(`/forms/${selectedId}/sections`, { name: sectionName, display_order: activeForm?.sections?.length ?? 0 }), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['form-definition', selectedId] }); setSectionName('') }, onError: () => setError('Could not create section.') })
  const createField = useMutation({ mutationFn: (sectionId: string) => api.post(`/forms/${selectedId}/fields`, { ...field, display_order: 0 }, { params: { section_id: sectionId } }), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['form-definition', selectedId] }); setField({ label: '', variable_name: '', control_type: 'text', data_type: 'string', is_required: false }) }, onError: () => setError('Could not create field.') })

  return <PageContainer><PageHeader title="Form Builder" description="Configure eCRF definitions on the current draft study version." ownership={<OwnershipBadge owner="EDC" />} />
    {error ? <Alert variant="destructive" className="mb-6"><AlertDescription>{error}</AlertDescription></Alert> : null}
    <div className="grid gap-6 lg:grid-cols-[18rem_1fr]">
      <Card><CardHeader className="pb-3"><div className="flex items-center justify-between"><CardTitle className="text-base">Forms</CardTitle><span className="text-xs text-muted-foreground">{formsQuery.data?.length ?? 0}</span></div></CardHeader><CardContent className="space-y-3">
        {formsQuery.isLoading ? <LoadingState label="form definitions" className="border-0 p-0 shadow-none" /> : formsQuery.error ? <ErrorState message="Form definitions could not be loaded." onRetry={() => void formsQuery.refetch()} /> : formsQuery.data?.length ? <div className="space-y-1">{formsQuery.data.map((item) => <Button type="button" key={item.id} variant={item.id === selectedId ? 'secondary' : 'ghost'} className="h-auto w-full justify-start px-3 py-2 text-left" onClick={() => setSelectedId(item.id)}><span><b>{item.form_code}</b> — {item.name}</span></Button>)}</div> : <EmptyState title="No forms yet" description="Create a form definition for this study version." />}
        {canConfigure ? <form className="space-y-3 border-t pt-4" onSubmit={(event) => { event.preventDefault(); createForm.mutate() }}><h3 className="text-sm font-medium">Add form</h3><div className="space-y-1.5"><Label htmlFor="form-name">Form name</Label><Input id="form-name" required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></div><div className="space-y-1.5"><Label htmlFor="form-code">Form code</Label><Input id="form-code" required value={form.form_code} onChange={(event) => setForm({ ...form, form_code: event.target.value })} /></div><label className="flex items-center gap-2 text-sm"><Checkbox checked={form.is_repeating} onChange={(event) => setForm({ ...form, is_repeating: event.target.checked })} />Repeating form</label><Button type="submit" className="w-full" pending={createForm.isPending} loadingText="Creating…">Create form</Button></form> : null}
      </CardContent></Card>
      <Card>{!activeForm ? <CardContent className="pt-6"><EmptyState title="Select a form to continue" description="Configure sections and fields for the selected form definition." /></CardContent> : <><CardHeader><CardTitle>{activeForm.name}</CardTitle><CardDescription>{activeForm.form_code} · {activeForm.is_repeating ? 'Repeating' : 'Non-repeating'}</CardDescription></CardHeader><CardContent className="space-y-5"><form className="flex flex-col gap-2 sm:flex-row" onSubmit={(event) => { event.preventDefault(); createSection.mutate() }}><Input required placeholder="New section name" aria-label="New section name" value={sectionName} onChange={(event) => setSectionName(event.target.value)} /><Button type="submit" variant="outline" pending={createSection.isPending} loadingText="Adding…">Add section</Button></form>{detailQuery.isLoading ? <LoadingState label="form definition" /> : detailQuery.error ? <ErrorState message="Form definition could not be loaded." onRetry={() => void detailQuery.refetch()} /> : <div className="space-y-4">{activeForm.sections?.map((section) => <Card key={section.id} className="shadow-none"><CardHeader className="pb-3"><CardTitle className="text-base">{section.name}</CardTitle></CardHeader><CardContent className="space-y-3"><div className="space-y-1">{section.fields?.map((item) => <div key={item.id} className="flex flex-wrap justify-between gap-2 rounded-md bg-muted/50 px-3 py-2 text-sm"><span>{item.label} <span className="text-muted-foreground">({item.variable_name})</span></span><span className="text-muted-foreground">{item.control_type}{item.is_required ? ' · required' : ''}</span></div>)}</div>{canConfigure ? <form className="grid gap-2 sm:grid-cols-4" onSubmit={(event) => { event.preventDefault(); createField.mutate(section.id) }}><Input required placeholder="Field label" aria-label="Field label" value={field.label} onChange={(event) => setField({ ...field, label: event.target.value })} /><Input required placeholder="Variable name" aria-label="Variable name" value={field.variable_name} onChange={(event) => setField({ ...field, variable_name: event.target.value })} /><select aria-label="Control type" value={field.control_type} onChange={(event) => setField({ ...field, control_type: event.target.value })} className="h-10 rounded-md border border-input bg-background px-2 text-sm">{CONTROL_TYPES.map((type) => <option key={type}>{type}</option>)}</select><Button type="submit" pending={createField.isPending} loadingText="Adding…">Add field</Button></form> : null}</CardContent></Card>)}</div>}</CardContent></>}
      </Card>
    </div>
  </PageContainer>
}
